/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafemanager.view;

import cafemanager.dao.ProductDAO;
import cafemanager.model.Product;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class MainFrame extends javax.swing.JFrame {
    private ProductDAO productDAO = new ProductDAO();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form LoginFrame
     */
    public MainFrame() {
        initComponents();
        this.setLocationRelativeTo(null); // Căn giữa màn hình
        loadTable();
    }
        
    private void loadTable() {
        try {
            List<Product> list = productDAO.getAllProducts();
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("ID");
            model.addColumn("Tên sản phẩm");
            model.addColumn("Giá");
            model.addColumn("Trạng thái");

            for (Product p : list) {
                Vector row = new Vector();
                row.add(p.getProductId());
                row.add(p.getProductName());
                row.add(p.getPrice());
                row.add(p.isActive() ? "Đang bán" : "Ngừng bán");
                model.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblHello = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        jTabbedPanel = new javax.swing.JTabbedPane();
        pOSPanel2 = new cafemanager.view.POSPanel();
        menuPanel1 = new cafemanager.view.MenuPanel();
        accountPanel1 = new cafemanager.view.AccountPanel();
        statsPanel1 = new cafemanager.view.StatsPanel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        lblHello.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblHello.setText(" Xin chào, Admin    ");
        jPanel1.add(lblHello, java.awt.BorderLayout.LINE_START);

        btnLogOut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLogOut.setText("Đăng xuất");
        jPanel1.add(btnLogOut, java.awt.BorderLayout.LINE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jTabbedPanel.setAlignmentX(2.0F);
        jTabbedPanel.setAlignmentY(2.0F);
        jTabbedPanel.addTab("SALES", null, pOSPanel2, "");
        jTabbedPanel.addTab("MENU", menuPanel1);
        jTabbedPanel.addTab("STAFF", accountPanel1);
        jTabbedPanel.addTab("STATS", statsPanel1);

        getContentPane().add(jTabbedPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private cafemanager.view.AccountPanel accountPanel1;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPanel;
    private javax.swing.JLabel lblHello;
    private cafemanager.view.MenuPanel menuPanel1;
    private cafemanager.view.POSPanel pOSPanel2;
    private cafemanager.view.StatsPanel statsPanel1;
    // End of variables declaration//GEN-END:variables
}
