/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafemanager.view;

import cafemanager.model.Account;
import cafemanager.util.SessionManager;

/**
 *
 * @author PC
 */
public class MainFrame extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(MainFrame.class.getName());

    /**
     * Creates new form LoginFrame
     */
    
    
    
    public MainFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        applyStyles();
        registerEvents();
    }

    public MainFrame(Account account) {
        initComponents();
        this.setLocationRelativeTo(null);
        applyStyles();
        registerEvents();
        applyAccount(account);
    }

    private void applyStyles() {
        setMinimumSize(new java.awt.Dimension(900, 550));
        setSize(1050, 620);

        lblHello.setFont(UIHelper.FONT_BASE.deriveFont(java.awt.Font.BOLD, 16f));
        UIHelper.styleButton(btnLogOut);
        btnLogOut.setPreferredSize(new java.awt.Dimension(110, 36));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 16, 12, 16));

        jTabbedPanel.setFont(UIHelper.FONT_BASE.deriveFont(java.awt.Font.BOLD, 14f));
        jTabbedPanel.setTitleAt(0, "Bán hàng");
        jTabbedPanel.setTitleAt(1, "Thực đơn");
        jTabbedPanel.setTitleAt(2, "Nhân viên");
        jTabbedPanel.setTitleAt(3, "Thống kê");
        jTabbedPanel.setTitleAt(4, "Hóa đơn");
    }

    private void registerEvents() {
        btnLogOut.addActionListener(evt -> handleLogout());
        jTabbedPanel.addChangeListener(evt -> handleTabChange());
        
        // Khi MenuPanel báo "có thay đổi", ta gọi hàm loadProducts() của POSPanel
        menuPanel1.setOnDataChangedCallback(() -> {
            if (pOSPanel2 != null) {
                pOSPanel2.loadProducts(); 
            }
        });
    }

    private void handleTabChange() {
        int index = jTabbedPanel.getSelectedIndex();
        if (index < 0) {
            return;
        }

        String title = jTabbedPanel.getTitleAt(index);
        if ("Hóa đơn".equalsIgnoreCase(title)) {
            invoiceHistoryPanel1.reloadInvoices();
        }
    }

    private void applyAccount(Account account) {
        if (account == null) {
            return;
        }

        lblHello.setText("Xin chào, " + account.getFullName());

        String role = account.getRole();
        if (role == null || !role.equalsIgnoreCase("ADMIN")) {
            jTabbedPanel.remove(menuPanel1);
            jTabbedPanel.remove(accountPanel1);
            jTabbedPanel.remove(statsPanel1);
            jTabbedPanel.remove(invoiceHistoryPanel1);
        }
    }

    private void handleLogout() {
        SessionManager.logout();
        LoginFrame loginFrame = new LoginFrame();
        loginFrame.setVisible(true);
        dispose();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblHello = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        jTabbedPanel = new javax.swing.JTabbedPane();
        pOSPanel2 = new cafemanager.view.POSPanel();
        menuPanel1 = new cafemanager.view.MenuPanel();
        accountPanel1 = new cafemanager.view.AccountPanel();
        statsPanel1 = new cafemanager.view.StatsPanel();
        invoiceHistoryPanel1 = new cafemanager.view.InvoiceHistoryPanel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        lblHello.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblHello.setText(" Xin chào, Admin    ");
        jPanel1.add(lblHello, java.awt.BorderLayout.CENTER);

        btnLogOut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLogOut.setText("Đăng xuất");
        jPanel1.add(btnLogOut, java.awt.BorderLayout.LINE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jTabbedPanel.setAlignmentX(2.0F);
        jTabbedPanel.setAlignmentY(2.0F);
        jTabbedPanel.addTab("SALES", null, pOSPanel2, "");
        jTabbedPanel.addTab("MENU", menuPanel1);
        jTabbedPanel.addTab("STAFF", accountPanel1);
        jTabbedPanel.addTab("STATS", statsPanel1);
        jTabbedPanel.addTab("BILL", invoiceHistoryPanel1);

        getContentPane().add(jTabbedPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private cafemanager.view.AccountPanel accountPanel1;
    private javax.swing.JButton btnLogOut;
    private cafemanager.view.InvoiceHistoryPanel invoiceHistoryPanel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPanel;
    private javax.swing.JLabel lblHello;
    private cafemanager.view.MenuPanel menuPanel1;
    private cafemanager.view.POSPanel pOSPanel2;
    private cafemanager.view.StatsPanel statsPanel1;
    // End of variables declaration//GEN-END:variables
}
